name: "test"

on:
  issues:
    types: [labeled]

jobs:
  add-card:
    runs-on: ubuntu-latest
    steps:
    - name: debug
      run: echo "${{ toJson(github) }}"
    - name: echo
      run: echo "${{ github.event.issue.id }}, ${{ github.event.issue.number }}"
    - uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.request('POST /projects/columns/{column_id}/cards', {
            'column_id': 18094552 
            'content_id': '${{ github.event.issue.id }}',
            'content_type': 'Issue'
          })
      
