name: "test"

on:
  issues:
    types: [labeled]

jobs:
  add-card:
    runs-on: ubuntu-latest
    steps:
    - name: debug
      run: echo "${{ toJson(github) }}"
    - name: echo
      run: echo "${{ github.event.issue.id }}, ${{ github.event.issue.number }}"
      
