name: "test"

on:
  issues:
    types: [labeled]

jobs:
  add-card:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH
      run: echo "${{ github.events.issue.id }}, ${{ github.events.issue.number }}"
      
